;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-paren
	c-electric-semi&comma
	c-electric-star
	c-indent-line-or-region
	electric-newline-and-maybe-indent
	))

(setq mc/cmds-to-run-once
      '(
	ace-window
	hydra-multiple-cursors/ignore
	hydra-multiple-cursors/mc/add-cursor-on-click
	hydra-multiple-cursors/mc/mark-all-dwim
	hydra-multiple-cursors/mc/mark-all-like-this-and-exit
	hydra-multiple-cursors/mc/mark-next-like-this
	hydra-multiple-cursors/mc/mark-next-word-like-this
	hydra-multiple-cursors/mc/mark-previous-like-this
	swiper-mc
	))
